{{ javascript_include('terminal/js/jquery-1.12.0.min.js') }}
{{ javascript_include('terminal/js/bootstrap/bootstrap.min.js') }}
{{ javascript_include('terminal/js/bootstrap/utils.js') }}
{{ javascript_include('terminal/js/jquery.uploadThumbs.js') }}
{{ javascript_include('terminal/js/gentelella/custom.min.js') }}
{{ javascript_include('terminal/js/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js') }}
{{ javascript_include('terminal/js/modal.js') }}
{{ javascript_include('terminal/js/confirm.js') }}
{{ javascript_include('terminal/js/footerFixed.js') }}
